### PR TITLE
Adds color pairing: text and icons section

### PR DESCRIPTION
**Pull request by patphongs**
This adds color pairings from this issue: https://github.com/18F/fec-pattern-library/issues/39

screen shot 2017-12-01 at 1 35 57 pm

### CODE REVIEW

**Comment by xtine** [comment]
Can you add a screenshot of your changes?

**Comment by patphongs** [comment]
> Can you add a screenshot of your changes?

Yes, just added, thanks!

**Comment by xtine** [comment]
I want to state that while markup for "hidden" components to show documentation data like this can utilize more inline styles while still dogfooding our own styles, and doesn't require the semantic markup and attention to detail that markup and styles in `fec-cms` requires. This is because the markup and inline styles for documentation components are not utilized outside of this section and custom.

Markup for actual components (accordions, filters, etc) should be more true to the actual semantic markup for utilization in `fec-cms`, but also can allow some inline styling for padding and placement specific to the window of the pattern library.

I am going to put ^^ into the `README.md`, but I just wanted to re-iterate as now FEC is going to start taking over more of the maintenance of this pattern library besides just myself.

**Comment by jenniferthibault** [comment]
@patphongs I think you made some commits that weren't synced or added in design pairing last week. Let's see if I can summarize them from memory:

- Replace each "Call to action" with the standard link styling
- Use custom styling to recreate the icons in circles here so that they can be exact (instead of copying classes implemented in production which make the icons inconsistently sized)

screen shot 2017-12-05 at 4 59 55 pm


I'm not sure if you'll have time to complete this before heading out, but wanted to catchup the discussion thread just in case.

**Comment by patphongs** [comment]
This is an outdated PR. Closing in favor of https://github.com/fecgov/fec-pattern-library/pull/105

**Pull request closed without merging**
