### PR TITLE
Add complete set of card components

### PR DESCRIPTION
**Pull request by jenniferthibault**
## Summary of changes

- Addresses #71 , #72 , #74 
- Creates a subcategories within the card component, for  horizontal, vertical, and major cards
- Adds known examples of each format
- Adds notes and documentation for each type

## Screenshots
screen shot 2018-03-30 at 2 18 47 am

screen shot 2018-04-06 at 11 26 01 am

screen shot 2018-03-30 at 2 19 18 am

### CODE REVIEW

**Comment by jenniferthibault** [comment]
Thanks for the great feedback @JonellaCulmer ! I adjusted the notes tab for Horizontal cards to read as follows:

screen shot 2018-04-02 at 12 39 35 pm


What do you think?

**Comment by JonellaCulmer** [comment]
Looks great, thanks @jenniferthibault!

There is one small typo on the second bullet under Guidance "...short _and_ direct".

**Comment by jenniferthibault** [comment]
😳 THANK YOU! Got it in one more commit

**Comment by jenniferthibault** [comment]
Nudge on this 👉 👉 👉  @johnnyporkchops can we get a review on this PR please?

**Pull request merged**
