### PR TITLE
Add filter validation pattern to components

### PR DESCRIPTION
**Pull request by jenniferthibault**
## Summary of changes

Adds component patterns for filter validation. This component is demonstrated in action in each filter component through a gif, but having them as a separate pattern makes them more visible, and provides a place for better explanation and history.

## Screenshots
screen shot 2018-03-30 at 5 43 00 pm
screen shot 2018-03-30 at 5 43 14 pm

### CODE REVIEW

**Comment by patphongs** [comment]
Oh looks like a bunch of js tests are failing @jenniferthibault. We pull in fec-cms develop branch into the pattern library. When the tests are run for fec-cms and they fail, circle build will fail. Will look into this.

**Comment by jenniferthibault** [comment]
@patphongs thanks! it's not actually this repo that's the problem though, was your comment meant for https://github.com/fecgov/fec-cms/pull/1894 ?

**Comment by patphongs** [comment]
oops, yes it was @jenniferthibault! I mixed up my PR comments :)

**Comment by jenniferthibault** [comment]
🙈 😳 thank you @JonellaCulmer !! I fixed 'em in a new commit.

**Comment by jenniferthibault** [comment]
Nudge on this 👉 👉 👉  @patphongs can we get a review on this PR please?

**Pull request merged**
