### PR TITLE
Update NPM packages

### PR DESCRIPTION
**Pull request by xtine**
Ran `npm update` to update packages.

### CODE REVIEW

**Comment by jenniferthibault** [comment]
@xtine thanks!

Generally how often should npm packages be updated, and what does the update change? Would you ever expect updating npm packages to break anything?

**Comment by xtine** [comment]
While there's no standard time cycle to update packages, this specific repo `npm update` needs to be run any time `fec-cms` is updated. Besides updating whenever the `fec-cms` dependency is updated, typically maybe dependencies should be checked every month.

**Comment by jenniferthibault** [comment]
@johnnyporkchops @patphongs you two should take a look at @xtine 's helpful note here about npm updates :) ☝️ Glad to hand off PR review for this to one of you

**Comment by xtine** [comment]
@patphongs: because the dependencies in this repo are independent `fec-cms`, it doesn't matter if they are in sync or not. However, it should be good practice in general to run `npm update` from time to time to get updated dependencies automatically rather than trying to manually check if dependencies have updated.

**Pull request merged**
