### PR TITLE
Update button component previews

### LINKED ISSUE #57: Adjust buttons component so that it's up to date and accurate
_Filed as a next step to #47_ 

In order to ensure that the pattern library shows the canonical of the accordion component, make 
the following changes:

**Changes to the basic category:**
- [x] Remove active state. The active state will be shown through the toggle component
- [x] Add more spacing between buttons so that they don't look so much like toggles

**Changes to the icon category:**
- [x] Show each button in just one color—color changes can be determined by the `basic` tab, and this will cut down clutter
- [x] Add dropdown buttons. These examples were missing from the components 

**Changes to the sizes category:**
 - [x] Remove the colored background slab to be consistent

### PR DESCRIPTION
**Pull request by jenniferthibault**
## Summary
- Updates the button component based on criteria set in #57 
  - Basic: Remove active state. The active state will be shown through the toggle component
  - Basic: Add more spacing between buttons so that they don't look so much like toggles
  - Icons: Show each button in just one color—color changes can be determined by the basic tab, and this will cut down clutter
  - Icons: Add dropdown buttons. These examples were missing from the components
  - Sizes: Remove the colored background slab to be consistent
- Adds additional toggle button examples discovered during research

screen shot 2018-02-26 at 9 51 06 am

screen shot 2018-02-26 at 9 50 52 am

screen shot 2018-02-26 at 9 50 36 am

## Notes for review
- If #54 is merged before this PR, redirect this toward the master branch and any merge conflicts will need to be resolved.
- The "dropdown" functionality does not work in the examples I included of dropdown buttons with icons, and I'm not quite sure why. I'd like to merge without the functionality, since it's still useful in this state, and file a separate issue for making them work as examples.
- Resolves #57

### CODE REVIEW

**Comment by xtine** [comment]
Which are the "dropdown buttons with icons?" I can see what is missing for them to work.

**Comment by jenniferthibault** [comment]
If you want to add a commit to make the dropdown buttons work, that would be amazing!

I included three examples in the buttons with icons section:
- Subscribe
- Download
- Add to calendar

The options that appear in the dropdown lists can get taked from the real examples of them in use on the calendar: https://www.fec.gov/calendar/

screen shot 2018-02-27 at 7 58 48 pm

**Comment by xtine** [comment]
Hooked up the button icon dropdowns:
screen shot 2018-02-27 at 6 52 31 pm

**Bonus**: got the favicon working!
screen shot 2018-02-27 at 6 54 39 pm

**Comment by jenniferthibault** [comment]
Woohoo! Thanks @xtine, I ran your additions locally and they look good, so since you approved the review, I'll merge 🔆

**Pull request merged**
